/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuspendedRouteImport } from './routes/suspended'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DRouteImport } from './routes/d'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DIndexRouteImport } from './routes/d.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as DShiftRouteImport } from './routes/d.shift'
import { Route as DReportRouteImport } from './routes/d.report'
import { Route as DProfileRouteImport } from './routes/d.profile'
import { Route as DLoginRouteImport } from './routes/d.login'
import { Route as AppWarehousesRouteImport } from './routes/_app.warehouses'
import { Route as AppEventsRouteImport } from './routes/_app.events'
import { Route as AppDriversRouteImport } from './routes/_app.drivers'
import { Route as AppDispatchRouteImport } from './routes/_app.dispatch'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as DRoutesJobIdRouteImport } from './routes/d.routes.$jobId'
import { Route as ApiPublicPairingLoginRouteImport } from './routes/api/public/pairing-login'
import { Route as ApiPublicCronShiftRolloverRouteImport } from './routes/api/public/cron/shift-rollover'

const SuspendedRoute = SuspendedRouteImport.update({
  id: '/suspended',
  path: '/suspended',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DRoute = DRouteImport.update({
  id: '/d',
  path: '/d',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DIndexRoute = DIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const DShiftRoute = DShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => DRoute,
} as any)
const DReportRoute = DReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => DRoute,
} as any)
const DProfileRoute = DProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DRoute,
} as any)
const DLoginRoute = DLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DRoute,
} as any)
const AppWarehousesRoute = AppWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversRoute = AppDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppRoute,
} as any)
const AppDispatchRoute = AppDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const DRoutesJobIdRoute = DRoutesJobIdRouteImport.update({
  id: '/routes/$jobId',
  path: '/routes/$jobId',
  getParentRoute: () => DRoute,
} as any)
const ApiPublicPairingLoginRoute = ApiPublicPairingLoginRouteImport.update({
  id: '/api/public/pairing-login',
  path: '/api/public/pairing-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronShiftRolloverRoute =
  ApiPublicCronShiftRolloverRouteImport.update({
    id: '/api/public/cron/shift-rollover',
    path: '/api/public/cron/shift-rollover',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/d': typeof DRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suspended': typeof SuspendedRoute
  '/alerts': typeof AppAlertsRoute
  '/dispatch': typeof AppDispatchRoute
  '/drivers': typeof AppDriversRoute
  '/events': typeof AppEventsRoute
  '/warehouses': typeof AppWarehousesRoute
  '/d/login': typeof DLoginRoute
  '/d/profile': typeof DProfileRoute
  '/d/report': typeof DReportRoute
  '/d/shift': typeof DShiftRoute
  '/admin/': typeof AdminIndexRoute
  '/d/': typeof DIndexRoute
  '/api/public/pairing-login': typeof ApiPublicPairingLoginRoute
  '/d/routes/$jobId': typeof DRoutesJobIdRoute
  '/api/public/cron/shift-rollover': typeof ApiPublicCronShiftRolloverRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suspended': typeof SuspendedRoute
  '/alerts': typeof AppAlertsRoute
  '/dispatch': typeof AppDispatchRoute
  '/drivers': typeof AppDriversRoute
  '/events': typeof AppEventsRoute
  '/warehouses': typeof AppWarehousesRoute
  '/d/login': typeof DLoginRoute
  '/d/profile': typeof DProfileRoute
  '/d/report': typeof DReportRoute
  '/d/shift': typeof DShiftRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/d': typeof DIndexRoute
  '/api/public/pairing-login': typeof ApiPublicPairingLoginRoute
  '/d/routes/$jobId': typeof DRoutesJobIdRoute
  '/api/public/cron/shift-rollover': typeof ApiPublicCronShiftRolloverRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/d': typeof DRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suspended': typeof SuspendedRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/dispatch': typeof AppDispatchRoute
  '/_app/drivers': typeof AppDriversRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/warehouses': typeof AppWarehousesRoute
  '/d/login': typeof DLoginRoute
  '/d/profile': typeof DProfileRoute
  '/d/report': typeof DReportRoute
  '/d/shift': typeof DShiftRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/d/': typeof DIndexRoute
  '/api/public/pairing-login': typeof ApiPublicPairingLoginRoute
  '/d/routes/$jobId': typeof DRoutesJobIdRoute
  '/api/public/cron/shift-rollover': typeof ApiPublicCronShiftRolloverRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/d'
    | '/login'
    | '/sitemap.xml'
    | '/suspended'
    | '/alerts'
    | '/dispatch'
    | '/drivers'
    | '/events'
    | '/warehouses'
    | '/d/login'
    | '/d/profile'
    | '/d/report'
    | '/d/shift'
    | '/admin/'
    | '/d/'
    | '/api/public/pairing-login'
    | '/d/routes/$jobId'
    | '/api/public/cron/shift-rollover'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sitemap.xml'
    | '/suspended'
    | '/alerts'
    | '/dispatch'
    | '/drivers'
    | '/events'
    | '/warehouses'
    | '/d/login'
    | '/d/profile'
    | '/d/report'
    | '/d/shift'
    | '/'
    | '/admin'
    | '/d'
    | '/api/public/pairing-login'
    | '/d/routes/$jobId'
    | '/api/public/cron/shift-rollover'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/d'
    | '/login'
    | '/sitemap.xml'
    | '/suspended'
    | '/_app/alerts'
    | '/_app/dispatch'
    | '/_app/drivers'
    | '/_app/events'
    | '/_app/warehouses'
    | '/d/login'
    | '/d/profile'
    | '/d/report'
    | '/d/shift'
    | '/_app/'
    | '/admin/'
    | '/d/'
    | '/api/public/pairing-login'
    | '/d/routes/$jobId'
    | '/api/public/cron/shift-rollover'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DRoute: typeof DRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuspendedRoute: typeof SuspendedRoute
  ApiPublicPairingLoginRoute: typeof ApiPublicPairingLoginRoute
  ApiPublicCronShiftRolloverRoute: typeof ApiPublicCronShiftRolloverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suspended': {
      id: '/suspended'
      path: '/suspended'
      fullPath: '/suspended'
      preLoaderRoute: typeof SuspendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d': {
      id: '/d'
      path: '/d'
      fullPath: '/d'
      preLoaderRoute: typeof DRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/': {
      id: '/d/'
      path: '/'
      fullPath: '/d/'
      preLoaderRoute: typeof DIndexRouteImport
      parentRoute: typeof DRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/d/shift': {
      id: '/d/shift'
      path: '/shift'
      fullPath: '/d/shift'
      preLoaderRoute: typeof DShiftRouteImport
      parentRoute: typeof DRoute
    }
    '/d/report': {
      id: '/d/report'
      path: '/report'
      fullPath: '/d/report'
      preLoaderRoute: typeof DReportRouteImport
      parentRoute: typeof DRoute
    }
    '/d/profile': {
      id: '/d/profile'
      path: '/profile'
      fullPath: '/d/profile'
      preLoaderRoute: typeof DProfileRouteImport
      parentRoute: typeof DRoute
    }
    '/d/login': {
      id: '/d/login'
      path: '/login'
      fullPath: '/d/login'
      preLoaderRoute: typeof DLoginRouteImport
      parentRoute: typeof DRoute
    }
    '/_app/warehouses': {
      id: '/_app/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AppWarehousesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drivers': {
      id: '/_app/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AppDriversRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dispatch': {
      id: '/_app/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof AppDispatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/d/routes/$jobId': {
      id: '/d/routes/$jobId'
      path: '/routes/$jobId'
      fullPath: '/d/routes/$jobId'
      preLoaderRoute: typeof DRoutesJobIdRouteImport
      parentRoute: typeof DRoute
    }
    '/api/public/pairing-login': {
      id: '/api/public/pairing-login'
      path: '/api/public/pairing-login'
      fullPath: '/api/public/pairing-login'
      preLoaderRoute: typeof ApiPublicPairingLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/shift-rollover': {
      id: '/api/public/cron/shift-rollover'
      path: '/api/public/cron/shift-rollover'
      fullPath: '/api/public/cron/shift-rollover'
      preLoaderRoute: typeof ApiPublicCronShiftRolloverRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppDispatchRoute: typeof AppDispatchRoute
  AppDriversRoute: typeof AppDriversRoute
  AppEventsRoute: typeof AppEventsRoute
  AppWarehousesRoute: typeof AppWarehousesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppDispatchRoute: AppDispatchRoute,
  AppDriversRoute: AppDriversRoute,
  AppEventsRoute: AppEventsRoute,
  AppWarehousesRoute: AppWarehousesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DRouteChildren {
  DLoginRoute: typeof DLoginRoute
  DProfileRoute: typeof DProfileRoute
  DReportRoute: typeof DReportRoute
  DShiftRoute: typeof DShiftRoute
  DIndexRoute: typeof DIndexRoute
  DRoutesJobIdRoute: typeof DRoutesJobIdRoute
}

const DRouteChildren: DRouteChildren = {
  DLoginRoute: DLoginRoute,
  DProfileRoute: DProfileRoute,
  DReportRoute: DReportRoute,
  DShiftRoute: DShiftRoute,
  DIndexRoute: DIndexRoute,
  DRoutesJobIdRoute: DRoutesJobIdRoute,
}

const DRouteWithChildren = DRoute._addFileChildren(DRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DRoute: DRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuspendedRoute: SuspendedRoute,
  ApiPublicPairingLoginRoute: ApiPublicPairingLoginRoute,
  ApiPublicCronShiftRolloverRoute: ApiPublicCronShiftRolloverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
