ALTER TYPE driver_event_type ADD VALUE IF NOT EXISTS 'JOB_CARD_SENT';
ALTER TYPE driver_event_type ADD VALUE IF NOT EXISTS 'CANT_COMPLETE';
ALTER TYPE driver_event_type ADD VALUE IF NOT EXISTS 'END_SHIFT_BLOCKED';